language: go
sudo: false
go:
  - 1.7.4
  - 1.9.2
  - tip
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
addons:
  apt:
    packages:
      - rsyslog
      - xmlsec1
install: true
before_script:
  - rsyslogd &
  - sleep 1
script:
  - go get -u golang.org/x/lint/golint
  - ls
  - $GOPATH/bin/golint ./...
# script:
  # - make test
  # - ./check-fmt.sh
  # - make deadcode
  # - go get golang.org/x/net/http2/...
  # - ./check-handlers.sh
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
services:
  - mongodb
  - redis
matrix:
  allow_failures:
    - go: tip
